### ISSUE TITLE
In the new version HA 2022.4.0 this error appears on the fan device 

### ISSUE THREAD

**Issue by dammx** [AlexxIT/SonoffLAN#738]
In the new version HA 2022.4.0
this error appears on the fan device 

![image](https://user-images.githubusercontent.com/50177086/162028683-4bd550e4-3d9d-4862-9fbb-25cbf8b5c149.png)

![image](https://user-images.githubusercontent.com/50177086/162028811-ad1f8637-4715-4ac9-b4da-e39203433007.png)

**Comment by pepe59** [comment]
I have the same problem after updating HA to version 2022.4.0

**Comment by Rikus102** [comment]
Same with Sonoff iFan03

**Comment by Phil-m-pinto** [comment]
I have the same problem

Logger: homeassistant.helpers.service
Source: helpers/service.py:130
First occurred: 8:38:51 PM (12 occurrences)
Last logged: 9:30:00 PM

Unable to find referenced entities fan.sonoff_1000cc2920
Unable to find referenced entities fan.sonoff_1000cc27c7, fan.sonoff_1000cc2920
Unable to find referenced entities fan.sonoff_1000cc27c7

&

Logger: homeassistant.setup
Source: setup.py:298
First occurred: 8:34:47 PM (2 occurrences)
Last logged: 8:34:47 PM

Unable to prepare setup for platform sonoff.fan: Platform not found (cannot import name 'SPEED_LOW' from 'homeassistant.components.fan' (/usr/src/homeassistant/homeassistant/components/fan/__init__.py)).  

after update to 2022.4.0

**Comment by Zipp0KMS** [comment]
The Fan platform is changed:
https://developers.home-assistant.io/docs/core/entity/fan

Hope for a fast update.

**Comment by garbovich** [comment]
Same here , only the fan light is still working 
Thanks

**Comment by RoadXY** [comment]
Duplicate of [#735](https://github.com/AlexxIT/SonoffLAN/issues/735)

**Comment by roymorrison** [comment]
Glad I read this, was about to start resetting things. I will wait for a fix.

**Comment by Rikus102** [comment]
I rolled back to core_2022.3.8 and everything is working again, will wait for a fix.

**Comment by dincojazz** [comment]
Same to me

**Comment by ahbrims** [comment]
Same for me

**Comment by dincojazz** [comment]
> Same to me

Me too rolled back to core_2022.3.8 and everything is working again, will wait for a fix.

**Comment by Xcat2008** [comment]
My Fan i3 stop also working :/ ( The following integrations and platforms could not be set up: sonoff.fan ) Only the light works from the sonoff IFan03.

**Comment by chemelli74** [comment]
Duplicate of #725

**Comment by MrStrathmore** [comment]
This was already warned about before the update.  Hopefully you all had the backup to rollback.

**Comment by odinb** [comment]
> This was already warned about before the update. Hopefully you all had the backup to rollback.

Not complaining or anything, but would like to know where this was communicated, because apparently I missed it! Did not see it on the release notes page for HA (breaking changes). I would have held off on updating if I had known.

**Comment by MrStrathmore** [comment]
> Not complaining or anything, but would like to know where this was communicated, because apparently I missed it! Do not want to miss it next time! Did not see it on the release notes page for HA (breaking changes). I would have held off on updating if I had known.

I don't recall the place I saw it.  Just remember that the removal of the ability to set speeds based on some preset value (low, medium etc) was to be removed and only to then be controllable via a percentage speed.  At the time, I had tried to see if the iFan would operate using this method and confirmed it did not.

Hopefully an update will be made.  The info looks like there is already some method to do conversion that needs included in the code.

**Comment by Phil-m-pinto** [comment]
> > Not complaining or anything, but would like to know where this was communicated, because apparently I missed it! Do not want to miss it next time! Did not see it on the release notes page for HA (breaking changes). I would have held off on updating if I had known.
> 
> I don't recall the place I saw it. Just remember that the removal of the ability to set speeds based on some preset value (low, medium etc) was to be removed and only to then be controllable via a percentage speed. At the time, I had tried to see if the iFan would operate using this method and confirmed it did not.
> 
> Hopefully an update will be made. The info looks like there is already some method to do conversion that needs included in the code.

I hope so. It seems odd to control a fan speed with percentage though. Surely low, medium and high was sufficient? And iFan surely can't be the only fan that works on low medium and high. To be honest, I've never seen a fan that has a percentage control.

**Comment by Xcat2008** [comment]
I'm new to this, i just wanna this working again.. Did not saw anything about changes or something... I'm happy with only the 3 speed´s, because my fan that was "not smart" had only 3 speed's.. So after applying the sonoff ifan3 i'm not able anymore of control it or even turn it on.. Percentage Fan is kinda stupid, dunno what people is trying to do... The only thing i can see to that apply is, some Fan's at first speed wonmt turn on or even spin... So maybe?! you are able now to set  "speed 1/low" percentage?! My fan was working great, but i read something about that, some not spinning...

**Comment by MrStrathmore** [comment]
> I hope so. It seems odd to control a fan speed with percentage though. Surely low, medium and high was sufficient? And iFan surely can't be the only fan that works on low medium and high. To be honest, I've never seen a fan that has a percentage control.

It will be related to how the speed control is achieved.  The iFan uses a combination of capacitors that are switched in to regulate the speed.  Other fans may use much more sophisticated methods.

**Comment by MrStrathmore** [comment]
> I'm new to this, i just wanna this working again.. Did not saw anything about changes or something... I'm happy with only the 3 speed´s, because my fan that was "not smart" had only 3 speed's.. So after applying the sonoff ifan3 i'm not able anymore of control it or even turn it on.. Percentage Fan is kinda stupid, dunno what people is trying to do... The only thing i can see to that apply is, some Fan's at first speed wonmt turn on or even spin... So maybe?! you are able now to set "speed 1/low" percentage?! My fan was working great, but i read something about that, some not spinning...

When you updated there should have been a backup made that you can restore through the supervisor panel.

**Comment by garbovich** [comment]
There is a temporary solution in another thread 

https://github.com/AlexxIT/SonoffLAN/issues/725

Its working great for me

**Comment by adizag** [comment]
Same Here
the solution from #725 didn't help.

**Comment by pepe59** [comment]
I use a diffuser and the solution didn't help either. Only light works. The fan does not work. Will there be a repair?

**Comment by roymorrison** [comment]
This worked for me,
https://github.com/AlexxIT/SonoffLAN/issues/735
Go hear follow instructions from pimw1 about half way down the page, ( Copy code and paste in fan.py ) reboot and all working again for me.
Regards Roy

**Comment by pepe59** [comment]
I followed the instructions, but it doesn't work. The fan entity is not created.

**Comment by AlexxIT** [comment]
Duplicate #735

**Comment by AlexxIT** [comment]
Fixed in v2.4.7
