### ISSUE TITLE
Fix cannot import name 'WSMessageTypeError' from 'aiohttp'

### ISSUE THREAD

**Issue by PetrNemec5** [AlexxIT/SonoffLAN#1647]
HomeAssistant cant load Sonoff, 

log below,
I can´t read (understand) this... 
happend after actualization :(

```
Logger: homeassistant.setup
Zdroj: setup.py:322
První výskyt: 13:59:13 (1 výskyty)
Naposledy logováno: 13:59:13

Setup failed for custom integration 'sonoff': Unable to import component: cannot import name 'WSMessageTypeError' from 'aiohttp' (/usr/local/lib/python3.12/site-packages/aiohttp/__init__.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/sonoff/__init__.py", line 28, in <module>
    from .core import devices as core_devices
  File "/config/custom_components/sonoff/core/devices.py", line 20, in <module>
    from .ewelink import XDevice
  File "/config/custom_components/sonoff/core/ewelink/__init__.py", line 8, in <module>
    from .cloud import XRegistryCloud
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 13, in <module>
    from aiohttp import (
ImportError: cannot import name 'WSMessageTypeError' from 'aiohttp' (/usr/local/lib/python3.12/site-packages/aiohttp/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 322, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1019, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/sonoff/__init__.py", line 28, in <module>
    from .core import devices as core_devices
  File "/config/custom_components/sonoff/core/devices.py", line 20, in <module>
    from .ewelink import XDevice
  File "/config/custom_components/sonoff/core/ewelink/__init__.py", line 8, in <module>
    from .cloud import XRegistryCloud
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 13, in <module>
    from aiohttp import (
ImportError: cannot import name 'WSMessageTypeError' from 'aiohttp' (/usr/local/lib/python3.12/site-packages/aiohttp/__init__.py)
```

**Comment by AlexxIT** [comment]
Show info about your HA installation.

**Comment by PetrNemec5** [comment]
Sorry, 
Home Assistant

Core   2024.7.2
Frontend   20240710.0

**Comment by AlexxIT** [comment]
And most importantly, how is your HA installed?

**Comment by PetrNemec5** [comment]
Raspberry OS 
Docker

**Comment by chuckzel** [comment]
I have the same problem after updating to v3.9 on a container install in docker on Debian. I'm Czech like the original poster, if that somehow could be relevant, though probably just a coincidence. My HA language is set to English.

My logs also show a warning about a blocking `importlib.import_module` call.

```
2025-08-18 21:03:27.368 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-08-18 21:03:27.368 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-08-18 21:03:27.369 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hass_agent which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-08-18 21:03:28.954 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module with args ('custom_components.sonoff',) in /usr/src/homeassistant/homeassistant/loader.py, line 1067: ComponentProtocol, importlib.import_module(self.pkg_path) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component
    result = await _async_setup_component(hass, domain, config)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1019, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)

2025-08-18 21:03:28.970 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'sonoff': Unable to import component: cannot import name 'WSMessageTypeError' from 'aiohttp' (/usr/local/lib/python3.12/site-packages/aiohttp/__init__.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/sonoff/__init__.py", line 28, in <module>
    from .core import devices as core_devices
  File "/config/custom_components/sonoff/core/devices.py", line 20, in <module>
    from .ewelink import XDevice
  File "/config/custom_components/sonoff/core/ewelink/__init__.py", line 8, in <module>
    from .cloud import XRegistryCloud
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 13, in <module>
    from aiohttp import (
ImportError: cannot import name 'WSMessageTypeError' from 'aiohttp' (/usr/local/lib/python3.12/site-packages/aiohttp/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1019, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/sonoff/__init__.py", line 28, in <module>
    from .core import devices as core_devices
  File "/config/custom_components/sonoff/core/devices.py", line 20, in <module>
    from .ewelink import XDevice
  File "/config/custom_components/sonoff/core/ewelink/__init__.py", line 8, in <module>
    from .cloud import XRegistryCloud
  File "/config/custom_components/sonoff/core/ewelink/cloud.py", line 13, in <module>
    from aiohttp import (
ImportError: cannot import name 'WSMessageTypeError' from 'aiohttp' (/usr/local/lib/python3.12/site-packages/aiohttp/__init__.py)
2025-08-18 21:03:29.759 WARNING (MainThread) [custom_components.hacs] <HacsData async_restore_repository> duplicate IDs The repo id for rt400/school-vacation is already set to 1040046512
2025-08-18 21:03:30.202 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:requestSync failed: 403
2025-08-18 21:04:29.613 ERROR (MainThread) [homeassistant.components.google_assistant.http] Request for https://homegraph.googleapis.com/v1/devices:reportStateAndNotification failed: 403

```

## System Information

version | core-2024.10.1
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.1.0-37-amd64
arch | x86_64
timezone | Europe/Prague
config_dir | /config

**Comment by chuckzel** [comment]
The issue seems to have disappeared after updating HA to the latest version (2025.8.2)

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.9.1
