### ISSUE TITLE
Unable to import component: cannot import name 'BinarySensorDeviceClass' from 

### ISSUE THREAD

**Issue by BoroBro** [AlexxIT/SonoffLAN#863]
After update to v3.0.5 and tried v3.0.4 has a problem.

Logger: homeassistant.setup
Source: setup.py:178
First occurred: 13:26:11 (1 occurrences)
Last logged: 13:26:11

Setup failed for sonoff: Unable to import component: cannot import name 'BinarySensorDeviceClass' from 'homeassistant.components.binary_sensor' (/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py)

HA in docker
2021.11.5

**Comment by BoroBro** [comment]
Support Hass v2021.12
