### ISSUE TITLE
Error in HomeAssistant 2025.6

### ISSUE THREAD

**Issue by martinstoehr** [AlexxIT/SonoffLAN#1620]
Since update to 2025.6 i have the following error:

```
Can't init device: {'name': 'TH16', 'deviceid': '1000f1faa3', 'apikey': 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'extra': {'uiid': 15, 'description': '20200807003', 'brandId': '5c4c1aee3a7d24c7100be054', 'apmac': 'd0:27:01:e3:f2:97', 'mac': 'd0:27:01:e3:f2:96', 'ui': '恒温恒湿改装件', 'modelInfo': '5c700feecc248c47441fd24f', 'model': 'PSA-BHA-GL', 'manufacturer': '深圳松诺技术有限公司', 'chipid': '00D87BB4', 'staMac': 'A4:CF:12:D8:7B:B4'}, 'brandName': 'SONOFF', 'brandLogo': 'https://eu-ota.coolkit.cc/logo/q62PevoglDNmwUJ9oPE7kRrpt1nL1CoA.png', 'showBrand': True, 'productModel': 'TH16R2', 'tags': {'disable_timers': [], 'm_8adf_acip': 'on', 'temperatureUnit': 'centigrade'}, 'devConfig': {}, 'settings': {'opsNotify': 0, 'opsHistory': 1, 'alarmNotify': 1, 'wxAlarmNotify': 0, 'wxOpsNotify': 0, 'wxDoorbellNotify': 0, 'appDoorbellNotify': 1}, 'devGroups': [], 'family': {'familyid': '5f917806df20fd000803279c', 'index': 0, 'roomid': '5f9179798a50ca0008f377ff'}, 'shareTo': [], 'devicekey': 'xxxxxxxxxxxxxxxxxxxxxxxxxxx', 'online': True, 'params': {'version': 8, 'sledOnline': 'on', 'init': 1, 'switch': 'off', 'fwVersion': '3.5.0', 'rssi': -61, 'staMac': 'A4:CF:12:D8:7B:B4', 'startup': 'off', 'pulse': 'off', 'pulseWidth': 500, 'sensorType': 'DS18B20', 'currentHumidity': 'unavailable', 'currentTemperature': '53.6', 'mainSwitch': 'on', 'deviceType': 'temperature', 'targets': [{'targetHigh': '53', 'reaction': {'switch': 'off'}}, {'targetLow': '45', 'reaction': {'switch': 'on'}}], 'timers': [{'mId': 'cd48da7b-0fc1-8c8b-7741-a0433f340e1d', 'type': 'repeat', 'at': '15 21 * * 1,2,3,4,5,6,0', 'coolkit_timer_type': 'repeat', 'enabled': 1, 'do': {'switch': 'off', 'mainSwitch': 'off'}}, {'mId': '2881a650-4cb4-5e02-8a47-f94b080898ba', 'type': 'repeat', 'at': '30 4 * * 0,1,2,3,4,5,6', 'coolkit_timer_type': 'repeat', 'enabled': 1, 'do': {'switch': 'on', 'mainSwitch': 'on'}}], 'only_device': {'ota': 'success'}, 'ssid': 'xxxxxxxxxx', 'bssid': 'xx:xxx:xx:xx:xx', 'password': 'xxxxxxxxxxxx', 'timeZone': 2}, 'isSupportGroup': False, 'isSupportedOnMP': True, 'isSupportChannelSplit': False, 'deviceFeature': {}}
Traceback (most recent call last):
  File "/config/custom_components/sonoff/core/entity.py", line 88, in __init__
    self.internal_update(None if self.event else params)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sonoff/core/entity.py", line 113, in internal_update
    self.set_state(params)
    ~~~~~~~~~~~~~~^^^^^^^^
  File "/config/custom_components/sonoff/climate.py", line 62, in set_state
    elif self.is_aux_heat:
         ^^^^^^^^^^^^^^^^
AttributeError: 'XClimateTH' object has no attribute 'is_aux_heat'
```

Can anyone help?

**Comment by jeffalmeida** [comment]
Also, after update to 2025.6 I have this error:

Logger: homeassistant
Source: custom_components/sonoff/__init__.py:266
integration: Sonoff ([documentation](https://github.com/AlexxIT/SonoffLAN), [issues](https://github.com/AlexxIT/SonoffLAN/issues))
First occurred: 11:28:51 AM (1 occurrence)
Last logged: 11:28:51 AM

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/sonoff/__init__.py", line 252, in internal_normal_setup
    await internal_cache_setup(hass, entry, devices)
  File "/config/custom_components/sonoff/__init__.py", line 266, in internal_cache_setup
    hass.config_entries.async_forward_entry_setup(entry, domain)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?

**Comment by Gferretta** [comment]
Ídem
Same error message

**Comment by pb-asbuilt** [comment]
Similar issue here:
```
Traceback (most recent call last):
  File "/config/custom_components/sonoff/core/entity.py", line 88, in __init__
    self.internal_update(None if self.event else params)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sonoff/core/entity.py", line 113, in internal_update
    self.set_state(params)
    ~~~~~~~~~~~~~~^^^^^^^^
  File "/config/custom_components/sonoff/climate.py", line 62, in set_state
    elif self.is_aux_heat:
         ^^^^^^^^^^^^^^^^
AttributeError: 'XClimateTH' object has no attribute 'is_aux_heat'
```

**Comment by pbutterworth** [comment]
Same issue here after 2025.6:
```
Traceback (most recent call last):
  File "/config/custom_components/sonoff/core/entity.py", line 88, in __init__
    self.internal_update(None if self.event else params)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sonoff/core/entity.py", line 113, in internal_update
    self.set_state(params)
    ~~~~~~~~~~~~~~^^^^^^^^
  File "/config/custom_components/sonoff/climate.py", line 62, in set_state
    elif self.is_aux_heat:
         ^^^^^^^^^^^^^^^^
AttributeError: 'XClimateTH' object has no attribute 'is_aux_heat'
```

**Comment by Ivar222** [comment]
Update/reinstall sonoff custom integration via HACS. Then is should work. It worked for me! :)

**Comment by martinstoehr** [comment]
sorry, not completed! can't reopen it!

**Comment by Ivar222** [comment]
Oke! :)

Mvg,

Ivar

Verzonden met Proton Mail Android

-------- Oorspronkelijk bericht --------
Op 17-06-2025 14:14, schreef Martin :

**Comment by tarmor1** [comment]
Question - does this bug mean updating 2025.6.x HA version renders currently my Sonoff's unusable? Or is it just an error in log?

**Comment by pbutterworth** [comment]
> Question - does this bug mean updating 2025.6.x HA version renders currently my Sonoff's unusable? Or is it just an error in log?

I think it only affects climate entities.
However, I only have sonof TH devices, so can't really say for sure.

**Comment by AlexxIT** [comment]
You can disable climate entity until problem will be resolved.

**Comment by caitotheonlypotato** [comment]
that attribute/feature has been deprecated.

There's some discussion here I found

https://developers.home-assistant.io/blog/2024/03/10/climate-aux-heater-deprecated/
https://github.com/home-assistant/architecture/discussions/932

**Comment by pbutterworth** [comment]
Fixed in PR:
https://github.com/AlexxIT/SonoffLAN/pull/1633

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/SonoffLAN/releases/tag/v3.9.0
